Feat: 공통 컴포넌트 중 태그, 디데이 구현
Team-Detective/tomatoes pull request #13
Opened 2024-10-13 13:48 UTC by StopSoo

## 변경 사항 설명
토마토들 서비스에서 사용될 태그 컴포넌트, 디데이 컴포넌트 구현

<img width="448" alt="Screenshot 2024-10-13 at 22 35 34" src="https://github.com/user-attachments/assets/77bffc3f-bfb6-441c-8ede-46b41d90c34a">

## 관련 이슈
#9 

## 변경 유형
- [X] 새로운 기능: 태그, 디데이 컴포넌트를 디자인에 알맞게 구현
- [X] 리팩토링 (기능 변경 없음)
    - tailwind CSS를 적용할 때 중복되는 부분이 많아 이를 상수로 빼서 적용.
    - 📁 _tailwind.config.ts_ 에서 미리 설정해놓았던 컬러 상수 적용.
    - 폰트가 적용되는 줄 알았는데 아니었던 ... 적용 완 🫡
    - D-day 컴포넌트 구현 시, 타입마다 필요로 하는 props의 개수를 다르게 적용 etc.

## 체크리스트
- [X] 내 코드가 프로젝트의 코드 컨벤션을 따르고 있습니다.
- [X] 필요한 경우, 주석을 추가했습니다.

## 추가 정보
제가 구현한 이 두 가지 컴포넌트는 반응형으로 할 필요가 없을 것 같아 적용하지 않고 마무리한 상태입니다. 적용해야 할지 같이 고민해주시면 감사하겠습니다 ( ◡̉̈ )

2024-10-13 14:12 UTC, hminah0215 requested changes
tailwind css를 상수로 적용해서 코드가 깔끔해진거 잘했어요! 저도 앞으로 그렇게 정리해서 작성하는 습관을 들여야겠네요 ㅎㅎ 
말씀하신 반응형은 전체적인(?) 적용까지는 필요없지만,,,, 모바일에서도 사용되는 배지니까 아래 사진처럼 작은 화면에서 봤을때, 뱃지에있는 글자 크기가 조정되는 정도로는 수정하시면 좋을 것 같습니다! 
![image](https://github.com/user-attachments/assets/b37aaed9-178e-42c3-845f-8108c240d49a)

2024-10-13 14:52 UTC, starcradle101 approved these changes
수고하셨습니다! 민아님께서 코멘트 주신 대로 반응형 처리만 하시면 될 것 같아요.
Conflict가 발생하는 부분은 제가 남긴 코멘트처럼 지수님이 사용하시는 컴포넌트를 제외한 나머지 불필요한 컴포넌트는 page.tsx에서 제거하시면 됩니다! 👍🏻

2024-10-13 14:52 UTC, starcradle101 commented on src/components/common/Dday.tsx
> +const baseTagStyle = "h-[33px] px-2 py-[3px] rounded-[999px] justify-center items-center gap-1.5 inline-flex";
이렇게 컴포넌트 파일 내부에서 상수로 빼서 관리할수도 있군요! 저도 이 방법으로 다음 이슈에서 작업해봐야겠어요 👍🏻

2024-10-13 14:52 UTC, starcradle101 commented on src/app/page.tsx
> +      <div className="flex gap-2 mb-4">
이 부분에서 현재 Conflict가 발생하고 있어서 아마 머지가 안 될 건데, 지수님이 사용하시는 컴포넌트만 제외하고 나머지 컴포넌트는 제거하셔도 됩니다!

2024-10-13 14:52 UTC, starcradle101 commented on tailwind.config.ts
> +        pretendard: ['Pretendard', 'sans-serif'],
현재 로컬 폰트로 Pretendard Variable을 사용하고 있는데, 혹시 폰트가 적용되지 않고 있었나요?

2024-10-13 15:13 UTC, StopSoo commented on tailwind.config.ts
> +        pretendard: ['Pretendard', 'sans-serif'],
아 그 때 우리 폰트 같이 적용할 때 어느 파일에서 적용한지 까먹었거든요 ...
저거 안 적어도 적용되는지 테스트해볼게요!

2024-10-13 15:18 UTC, StopSoo commented on tailwind.config.ts
> +        pretendard: ['Pretendard', 'sans-serif'],
확인해보니 tailwind 사용할 때 제가 잘못 작성했던 것 ...! ㅎㅎ
수정 완료요 🫡

2024-10-14 00:41 UTC, hminah0215 approved these changes
작업 수고하셨습니다!

2024-10-14 01:19 UTC, kitae0831 approved these changes
같은 스타일의 작업에 있어서 어찌 해야할까 잠시 고민만하고 지나갔었는데, 
지수님 코드를 보니까 위에서 스타일을 정리하고 상황에 맞춰서 활용하면 되겠네요! 멋져요!
고생하셨습니다🙃

2024-10-14 02:06 UTC, merged